# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21e60554e0cba57b9ca325a986c7154e2947b83b15849395aa5af74c5c29c9725ee6b888b3c8c82f56c65e6f8ca33ec9169ac4fe0c648c97e7c1753486b471f0

test:
  secret_key_base: e0fc4707248625e068d4c4b87c70cf2ad577b9deafae217c64db2f6a2f1fca93176e021d54e7ef766837e7ce5709c3ea359524f8a816bedb835e84effe34afe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
